### ISSUE TITLE
Remove Routing namespace

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ApiBundle#106]
All classes under `Routing` are not necessary. We have to generate and inject routes directly on loading of the kernel. So it has to be implemented in DI extension or compiler pass.

**Comment by murnieza** [comment]
This is exactly what is going on under `Routing` namespace. It follows standard routes generation as described in [documentation](http://symfony.com/doc/current/cookbook/routing/custom_route_loader.html#creating-a-custom-loader).

Closing the issue. Feel free to reopen it if you think that we need to do any improvements.
