### ISSUE TITLE
Do not inject routes by listener. 

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ApiBundle#108]
There is two possible options here. Create a router for the chain or inject routes directly in to the Symfony router. The easier way would be the injection, I propose to stick with that.

After this issue implementation we don't need anymore anything under `EventListener` namespace unless it's related with the data events but not with the routing.

**Comment by murnieza** [comment]
Listeners under `EventListener` namespace are used only for "decorating" requests and handling errors. Routes are generated by standard Symfony's [custom loader](http://symfony.com/doc/current/cookbook/routing/custom_route_loader.html#creating-a-custom-loader) so they get cached and are generated only on warmup.

Do we want to change anything with `RestRequest`?

**Comment by saimaz** [comment]
Yeaahh, seems like EventListener only modifies request before kernel event. Anyway, no we do not need `RestRequest` at all. But we already discussed about it.

**Comment by murnieza** [comment]
It will be removed with https://github.com/ongr-io/ApiBundle/issues/107
