### ISSUE TITLE
Create controller which generates docs

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ApiBundle#23]
There is not clear task how it should be done. So we need to do a little research here.

All the details and proposals lets discuss here.

**Comment by saimaz** [comment]
- [ ] Research a plan how to generate doc fo API endpoints (@trylika might know the solution)
- [ ] Do it

**Comment by trylika** [comment]
Along with standard solution for Symfony ( https://github.com/FriendsOfSymfony/FOSRestBundle ) usually developers use https://github.com/nelmio/NelmioApiDocBundle to document API through annotations, we could use it or learn from it and do it ourselves.
