### ISSUE TITLE
Investigate the need of `Request\RestRequest`, `Request\RestRequestFactory`, `Request\RestRequestProxy`

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ApiBundle#98]
Do we need those classes to generate routes? 

Blocks https://github.com/ongr-io/ApiBundle/issues/94

**Comment by trandangtri** [comment]
IMO, when we simplified the BATCH command, I cannot find the reason which we need to use these classes anymore. I removed the proxy class in my work; and the near future, I think I will remove the Factory class too.

**Comment by saimaz** [comment]
Good, I also thought that we dont need those clases, just created this issue as a double check.
