### ISSUE TITLE
Implement getAll action in RestController

### ISSUE THREAD

**Issue by saimaz** [ongr-io/ApiBundle#99]
More info: https://github.com/ongr-io/ApiBundle/blob/9610b53ea5bc7dd3390b4be27e7a94452a3e4cb8/Resources/doc/endpoints.md#get-all-documents

**Comment by trandangtri** [comment]
As discussed, I want to detach this method from `RestController` and attach it into `AbstractCollectionController`. Now `RestController` just focuses on CRUD only.

And this is the definition of `AbstractCollectionController`
https://github.com/trandangtri/ApiBundle/blob/1.0/Controller/AbstractCollectionController.php

**Comment by saimaz** [comment]
After some investigation best way to implement `_all` and `_batch` operations would be by separating it in different controllers. I will create new issues for it.
